name: Fetch PR Files Action
description: Fetches files from a GitHub pull request

inputs:
  owner:
    description: "GitHub repository owner"
    required: true
  repo:
    description: "GitHub repository name"
    required: true
  pull_number:
    description: "Pull request number"
    required: true
  token:
    description: "GitHub authentication token"
    required: true

outputs:
  files:
    description: "Fetched files from the pull request"

runs:
  using: "node16"
  main: "index.js"
