name: Fetch PR Files Action
description: Fetches files from a GitHub pull request

inputs:
  owner:
    description: "GitHub repository owner"
    required: true
  repo:
    description: "GitHub repository name"
    required: true
  pull_number:
    description: "Pull request number"
    required: true
  PAT:
    description: "GitHub authentication token"
    required: true
  api_key:
    description: "OpenAI API Key"
    required: true


runs:
  using: "node16"
  main: "dist/index.js"
